// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RentARide.Infrastructure.Data;

#nullable disable

namespace RentARide.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RentARide.Domain.Entities.Amenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("Amenities");
                });

            modelBuilder.Entity("RentARide.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("RentARide.Domain.Entities.Rental", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Rentals");
                });

            modelBuilder.Entity("RentARide.Domain.Entities.RentalAmenity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AmenityId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RentalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("RentalAmenities");
                });

            modelBuilder.Entity("RentARide.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RentARide.Domain.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DailyPrice")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdb1404a-32ed-471c-9257-74e2f700a42e"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9171),
                            DailyPrice = 45.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-001",
                            Model = "Toyota Camry",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("99570827-9687-4bd3-9e2b-c32161c3630b"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9261),
                            DailyPrice = 48.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-002",
                            Model = "Honda Accord",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("7b115112-e4be-41c1-bb50-170141ede341"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9264),
                            DailyPrice = 40.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-003",
                            Model = "Hyundai Elantra",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("b77152d6-871d-4e92-bc61-a9cfcde33096"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9276),
                            DailyPrice = 42.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-004",
                            Model = "Nissan Altima",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("f4a71681-7c29-4a5b-a70c-2cea80bdd745"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9279),
                            DailyPrice = 46.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-005",
                            Model = "Mazda 6",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("29f7a11f-af13-4211-8edf-ef2abd496713"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9281),
                            DailyPrice = 47.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-006",
                            Model = "Volkswagen Passat",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("782dc1fa-4747-456a-998f-d9d6494795eb"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9282),
                            DailyPrice = 44.00m,
                            IsDeleted = false,
                            LicensePlate = "SED-007",
                            Model = "Kia K5",
                            Status = 1,
                            VehicleTypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("5cfc3a96-5935-49cf-99a1-f97425fa6831"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9284),
                            DailyPrice = 70.00m,
                            IsDeleted = false,
                            LicensePlate = "SUV-001",
                            Model = "Toyota RAV4",
                            Status = 1,
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("b3cdf568-5d60-437d-89e3-ee497eab0665"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9286),
                            DailyPrice = 68.00m,
                            IsDeleted = false,
                            LicensePlate = "SUV-002",
                            Model = "Honda CR-V",
                            Status = 1,
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("607c0878-5bb5-4c0b-af46-e860ec0a4129"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9290),
                            DailyPrice = 75.00m,
                            IsDeleted = false,
                            LicensePlate = "SUV-003",
                            Model = "Ford Explorer",
                            Status = 1,
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("d71bddab-7aeb-4f8a-a4e8-c06760f603a2"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9292),
                            DailyPrice = 65.00m,
                            IsDeleted = false,
                            LicensePlate = "SUV-004",
                            Model = "Hyundai Tucson",
                            Status = 1,
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("f1c0a257-96e8-4a0b-865d-cded209e2124"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9294),
                            DailyPrice = 72.00m,
                            IsDeleted = false,
                            LicensePlate = "SUV-005",
                            Model = "Mazda CX-5",
                            Status = 1,
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("5db3dc57-371a-4dac-ab0b-665b49ead97e"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9295),
                            DailyPrice = 80.00m,
                            IsDeleted = false,
                            LicensePlate = "SUV-006",
                            Model = "Jeep Grand Cherokee",
                            Status = 1,
                            VehicleTypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("4d52fc0e-59b4-4e52-88e0-7cb970edda97"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9297),
                            DailyPrice = 120.00m,
                            IsDeleted = false,
                            LicensePlate = "LUX-001",
                            Model = "BMW 5 Series",
                            Status = 1,
                            VehicleTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("3c70ba28-1cac-48ad-83cc-091751a61596"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9299),
                            DailyPrice = 130.00m,
                            IsDeleted = false,
                            LicensePlate = "LUX-002",
                            Model = "Mercedes E-Class",
                            Status = 1,
                            VehicleTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("dab21cd1-c428-48c2-b97b-7004ab4be977"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9301),
                            DailyPrice = 125.00m,
                            IsDeleted = false,
                            LicensePlate = "LUX-003",
                            Model = "Audi A6",
                            Status = 1,
                            VehicleTypeId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("f4e01023-676b-420f-91f3-8ba780801d49"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9302),
                            DailyPrice = 85.00m,
                            IsDeleted = false,
                            LicensePlate = "VAN-001",
                            Model = "Toyota Sienna",
                            Status = 1,
                            VehicleTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Year = 2023
                        },
                        new
                        {
                            Id = new Guid("291bda45-3de5-4e09-8f9a-40ee79fb5cd0"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9305),
                            DailyPrice = 88.00m,
                            IsDeleted = false,
                            LicensePlate = "VAN-002",
                            Model = "Honda Odyssey",
                            Status = 1,
                            VehicleTypeId = new Guid("44444444-4444-4444-4444-444444444444"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("e41f11ad-b136-40f5-989d-c8ed48e81b99"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9307),
                            DailyPrice = 95.00m,
                            IsDeleted = false,
                            LicensePlate = "SPT-001",
                            Model = "Ford Mustang",
                            Status = 1,
                            VehicleTypeId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Year = 2024
                        },
                        new
                        {
                            Id = new Guid("d062f4da-d64e-4472-b45a-e91aa3faf68a"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(9309),
                            DailyPrice = 90.00m,
                            IsDeleted = false,
                            LicensePlate = "SPT-002",
                            Model = "Chevrolet Camaro",
                            Status = 1,
                            VehicleTypeId = new Guid("55555555-5555-5555-5555-555555555555"),
                            Year = 2023
                        });
                });

            modelBuilder.Entity("RentARide.Domain.Entities.VehicleMaintenance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("LastMaintenanceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("NextMaintenanceDue")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("VehicleMaintenances");
                });

            modelBuilder.Entity("RentARide.Domain.Entities.VehicleType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(5125),
                            Description = "Comfortable 4-door passenger cars, fuel efficient and perfect for city driving",
                            IsDeleted = false,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(5305),
                            Description = "Spacious sport utility vehicles, perfect for families and outdoor adventures",
                            IsDeleted = false,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(5307),
                            Description = "Premium vehicles with advanced features and ultimate comfort",
                            IsDeleted = false,
                            Name = "Luxury"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(5308),
                            Description = "Large passenger capacity vehicles, ideal for group travel",
                            IsDeleted = false,
                            Name = "Van"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 2, 5, 22, 57, 45, 112, DateTimeKind.Utc).AddTicks(5309),
                            Description = "High-performance vehicles for an exhilarating driving experience",
                            IsDeleted = false,
                            Name = "Sports Car"
                        });
                });

            modelBuilder.Entity("RentARide.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("RentARide.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleType");
                });
#pragma warning restore 612, 618
        }
    }
}
